config/routes.rb
Facturadormx::Application.routes.draw do

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do

    resources :accounts
    resources :companies
    
    devise_for :users
    # override
    get "accounts/new" => "accounts#new", :as => "new_user_registration"
    
    get "dashboard/index" => 'dashboard#index'
    resources :people

    resources :line_items
    resources :items
    resources :invoices
    resources :organizations

    root :to => "dashboard#index"
    
  end
  match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  match '', to: redirect("/#{I18n.default_locale}")

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base

  belongs_to :account
  validates :account_id, :presence => true

  belongs_to :organization
  has_many :line_items, :dependent => :destroy

  validates_presence_of :organization_id, :invoice_number, :issued_on, :status
  # validates_uniqueness_of :invoice_number
  
  scope :newest, :order => "issued_on desc"

  accepts_nested_attributes_for :line_items, :reject_if => :reject_line_items, :allow_destroy => true
  def reject_line_items(attributed)
    attributed['item_id'].blank?
  end

  after_initialize :default_values
  def default_values
    self.status = 'sent' unless self.status
  end
  
  def subtotal
    line_items.to_a.sum { |item| item.line_total }
  end

  def iva
    (self.subtotal * 0.16).round(2)
  end
  
  def total
    (self.subtotal + self.iva).round(2)
  end

  def read_date_created_at
    created_at.strftime("%B %d, %Y")
  end

  def read_date_issued_on
    issued_on.strftime("%B %d, %Y")
  end
  
  def abbreviated_created_at
		created_at.strftime("%a %b %d at %I:%M%P")
	end
  
  def min_created_at
		created_at.strftime("%D")
	end
  
  def min_issued_on
		issued_on.strftime("%D")
	end

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController

  before_filter :authenticate_user!
  before_filter :load_resources, :only => [:new, :create, :edit, :update]

  def index
    @invoices = Invoice.where(:account_id => current_user.account.id).page(params[:page]).per(15)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @invoices }
    end
  end

  def show
    @invoice = Invoice.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

 def new
    @invoice = Invoice.new
    3.times do
      line_item = @invoice.line_items.build
    end
    @invoice.account_id = current_user.account.id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @invoice }
    end
  end

  def edit
    @invoice = Invoice.find(params[:id])
  end

  def create
    @invoice = Invoice.new(params[:invoice])
    @invoice.account_id = current_user.account.id

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render json: @invoice, status: :created, location: @invoice }
      else
        format.html { render action: "new" }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @invoice = Invoice.find(params[:id])

    respond_to do |format|
      if @invoice.update_attributes(params[:invoice])
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice = Invoice.find(params[:id])
    @invoice.destroy

    respond_to do |format|
      format.html { redirect_to invoices_url }
      format.json { head :ok }
    end
  end
  
  private
  
  def load_resources
    @clients = Organization.where(:account_id => current_user.account.id)
    @items = Item.where(:account_id => current_user.account.id)
  end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
  def link_to_remove_fields_invoice(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields_invoice(this)", :class => "delete")
  end

  def link_to_add_fields_invoice(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    # needed to remove the h call or javascript would be printed on the page
    # link_to_function(name, h("add_fields(this, '#{association}', '#{escape_javascript(fields)}')"))
    # the one below is the good one, I just had to customize it to accomodate it to the table
    link_to_function(name, "add_fields_invoice(this, '#{association}', '#{escape_javascript(fields)}')")
    # link_to_function(name, "add_fields(test, '#{association}', '#{escape_javascript(fields)}')")
  end
end

app/views/invoices/_form.html.erb
<style>
/*
	 CSS-Tricks Example
	 by Chris Coyier
	 http://css-tricks.com
*/

* { margin: 0; padding: 0; }
/* form.form-horizontal { font: 14px/1.4 Georgia, serif; } */
#page-wrap { width: 800px; margin: 0 auto; }

// textarea { border: 0; font: 14px Georgia, Serif; overflow: hidden; resize: none; }
table { border-collapse: collapse; }
table td, table th { border: 1px solid #CCC; padding: 5px; }

#header { height: 15px; width: 100%; margin: 20px 0; background: #222; text-align: center; color: white; font: bold 15px Helvetica, Sans-Serif; text-decoration: uppercase; letter-spacing: 20px; padding: 8px 0px; }

#address { width: 250px; height: 150px; float: left; }
#customer { overflow: hidden; }

#logo { text-align: right; float: right; position: relative; margin-top: 25px; border: 1px solid #fff; max-width: 540px; max-height: 100px; overflow: hidden; }
#logo:hover, #logo.edit { border: 1px solid #000; margin-top: 0px; max-height: 125px; }
#logoctr { display: none; }
#logo:hover #logoctr, #logo.edit #logoctr { display: block; text-align: right; line-height: 25px; background: #eee; padding: 0 5px; }
#logohelp { text-align: left; display: none; font-style: italic; padding: 10px 5px;}
#logohelp input { margin-bottom: 5px; }
.edit #logohelp { display: block; }
.edit #save-logo, .edit #cancel-logo { display: inline; }
.edit #image, #save-logo, #cancel-logo, .edit #change-logo, .edit #delete-logo { display: none; }
#customer-title { font-size: 20px; font-weight: bold; float: left; }

#meta { margin-top: 1px; width: 300px; float: right; }
#meta td { text-align: right;  }
#meta td.meta-head { text-align: left; background: #eee; }
#meta td textarea { width: 100%; height: 20px; text-align: right; }

#items { clear: both; width: 100%; margin: 30px 0 0 0; border: 1px solid #CCC; }
#items th { background: #eee; }
#items textarea { width: 80px; height: 50px; }

// #items tr.item-row td { border: 0; vertical-align: top; }
#items tr.item-row td {border:1px solid #CCC;}

#items tr.item-row td { vertical-align: top; }
#items td.description { width: 300px; }
#items td.item-name { width: 175px; }
#items td.description textarea, #items td.item-name textarea { width: 100%; }
#items td.total-line { border-right: 0; text-align: right; }
#items td.total-value { border-left: 0; padding: 10px; }
#items td.total-value textarea { height: 20px; background: none; }
#items td.balance { background: #eee; }
#items td.blank { border: 0; }


#terms { text-align: left; margin: 20px 0 0 0; }
#terms h5 { font: 13px Helvetica, Sans-Serif; margin: 0 0 3px 0; font-weight:bold; }
/*
#terms textarea { width: 100%; text-align: center;}
*/

textarea:hover, textarea:focus, #items td.total-value textarea:hover, #items td.total-value textarea:focus, .delete:hover { background-color:#FFF8D5; }

.delete-wpr { position: relative; }
.delete { display: block; color: #000; text-decoration: none; position: absolute; background: #EEEEEE; font-weight: bold; padding: 0px 3px; border: 1px solid; top: -6px; left: -22px; font-family: Verdana; font-size: 12px; }

/* Override bootstrap styling  */
textarea.description, input.price, input.qty{
  -webkit-box-shadow:none;
  box-shadow:none;
  border:none;  
}

textarea#invoice_notes{
  text-align:left;
}
</style>




<% if @invoice.errors.any? %>
<div class="flash">
    <div class="message error" style="padding-left:60px;text-align:left;">
      <p><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</p>
      <p>
        <ul style="padding-left:30px;">
        <% @invoice.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </p>
    </div>  
  </div>
<% end %>




<div id="page-wrap">

<%= simple_form_for @invoice, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.error_notification %>
  <%= f.association :organization, :collection => @clients, :label => t('invoices.form.client') %>
  <%= f.input :invoice_number, :label => t('invoices.form.invoice_number') %>
  <%= f.input :issued_on, :label => t('invoices.form.issued_on'), :as => :string %>



<table id="items">
		
		  <tr>
		      <th><%= t '.item' %></th>
		      <th><%= t '.description' %></th>
		      <th><%= t '.quantity' %></th>
		      <th><%= t '.unit_cost' %></th>
		      <th><%= t '.line_total' %></th>
		  </tr>
      
      <%= f.fields_for :line_items do |builder| %>
        <%= render 'line_item_fields', :f => builder %>
      <% end %>
		  
		  
		  
		  <tr id="hiderow" class="add_a_line_row">
		    <td colspan="5"><%= link_to_add_fields_invoice t(".add_a_line"), f, :line_items %></td>
		  </tr>
		  
		  <tr>
		      <td colspan="2" class="blank"> </td>
		      <td colspan="2" class="total-line">Subtotal</td>
		      <td class="total-value"><span id="total-price">input quantities</span></td>
		  </tr>

		  <!--
		  <tr>
		      <td colspan="2" class="blank"> </td>
		      <td colspan="2" class="total-line">Total</td>
		      <td class="total-value"><div id="total">$875.00</div></td>
		  </tr>
		  <tr>
		      <td colspan="2" class="blank"> </td>
		      <td colspan="2" class="total-line">Amount Paid</td>

		      <td class="total-value"><textarea id="paid">$0.00</textarea></td>
		  </tr>
		  <tr>
		      <td colspan="2" class="blank"> </td>
		      <td colspan="2" class="total-line balance">Balance Due</td>
		      <td class="total-value balance"><div class="due">$875.00</div></td>
		  </tr>
		  -->
		
		</table>

    <div id="terms">
		  <h5><%= t '.notes' %></h5>
		  
		  <%= f.text_area :notes, :rows => 3, :class => 'input-xlarge' %>
		  
		</div>
</div><!-- div#page-wrap ends -->

  <div class="form-actions">
    <%= f.button :submit, :value => t('buttons.new_invoice'), :class => 'btn-primary' %>
    <%= link_to t('buttons.cancel'), invoices_path, :class => 'btn' %>
  </div>
<% end %>

<script type="text/javascript">
$('textarea').autoResize({
  extraSpace: 5
});
</script>

app/views/invoices/_line_item_fields.html.erb
      <tr class="item line_item_row item-row">
		      <td class="item-name">
		        <div class="delete-wpr">
		          <%= f.select(:item_id, options_for_select(@items.map{|c| [c.name, c.id, {'data-defaultquantity'=>1,'data-price'=>c.price, 'data-description'=>c.description}]}, f.object.item_id), {:prompt => ''}, {:class=>'product', :style => 'width:105px;'}) %>
		          <%= link_to_remove_fields_invoice "X", f %>
		        </div>
		      </td>
		      <td class="description">
		        <%= f.text_area :description, :rows => 1, :value => f.object.description, :class => 'description' %>
		      </td>
		      <td class="quantity_data">
		        <%= f.text_field :quantity, :size => 4, :class => 'qty' %>
		      </td>
		      <td class="price_data" style="text-align:right;">
		        <%= f.text_field :price, :size => 8, :value => (number_with_precision(f.object.price,:precision => 2)||0), :class => 'price' %>
		      </td>
		      <td class="lineitemtotal linetotal_data" style="text-align:right;"></td>
		  </tr>

app/views/invoices/edit.html.erb
<fieldset>
  <legend>Editar Factura</legend>

  <%= render :partial => 'form' %>

</fieldset>

app/views/invoices/index.html.erb
<%- model_class = Invoice.new.class -%>

<div class="page-header">
<h1><%=t ".title" %></h1>
</div>

<% if @invoices.count > 0 %>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th><%= t ".invoice" %></th>
      <th><%= t ".client_name" %></th>
      <th><%= t ".date" %></th>
      <th style="text-align:right;">Total</th>
      <th style="text-align:center;">Status</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= link_to invoice.invoice_number, invoice_path(invoice) %></td>
        <td><%= invoice.organization.name.blank? ? "N/A" : invoice.organization.name %></td>
        <td><%= invoice.issued_on %></td>
        <td style="text-align:right;"><%= number_to_currency invoice.total %></td>
        <td style="text-align:center;">
          <%
            if invoice.status == 'paid'
              invoice_status_class = 'label label-success'
              read_status = t 'invoices.status.paid'
            elsif invoice.status == 'partial'
              invoice_status_class = 'label label-warning'
              read_status = t 'invoices.status.partial'
            else
              invoice_status_class = 'label label-important'
              read_status = t 'invoices.status.unpaid'
            end
            %>  
            <span class="<%= invoice_status_class %>"><%= read_status %></span>
        </td>
        <td>
          <%= link_to t('buttons.edit'),
                      edit_invoice_path(invoice), :class => 'btn btn-mini' %>
          <%= link_to t('buttons.destroy'),
                      invoice_path(invoice),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% else %>

<div class="alert alert-info">
  <h2>Desde aqui podras accesar tus facturas.
</div>

<% if Item.where(:account_id => current_user.account.id).count == 0 %>
  <div class="alert alert-block">
    Antes de capturar tu primer factura, hay que capturar por lo menos un concepto de facturacion.<h2>
    <%= link_to 'Haz click aqui para crear un nuevo concepto de facturacion', new_item_path, :class => 'btn btn-small btn-warning' %>
  </div>
<% end %>

<% if Organization.where(:account_id => current_user.account.id).count == 0 %>
  <div class="alert alert-block">
    Antes de capturar tu primer factura, hay que capturar por lo menos un cliente.<h2>
    <%= link_to 'Haz click aqui para crear un nuevo cliente', new_organization_path, :class => 'btn btn-small btn-warning' %>
  </div>
<% end %>

<% end %>

<%= link_to t('buttons.new_invoice'),
            new_invoice_path,
            :class => 'btn btn-primary' %>

app/views/invoices/new.html.erb
<fieldset>
  <legend>Crear Factura</legend>

  <%= render :partial => 'form' %>

</fieldset>

app/views/invoices/show.html.erb
<style>
/*
	 CSS-Tricks Example
	 by Chris Coyier
	 http://css-tricks.com
*/

* { margin: 0; padding: 0; }
// body { font: 14px/1.4 Georgia, serif; }
#page-wrap {
  width: 800px; margin: 0 auto;
  border:solid 1px #E1E1E1;
  padding: 54px 40px 72px 40px;
  -webkit-box-shadow: 2px 2px 4px rgba(0,0,0,0.15);
  -moz-box-shadow: 2px 2px 4px rgba(0,0,0,0.15);
  box-shadow: 2px 2px 4px rgba(0,0,0,0.15);
}

textarea { border: 0; font: 14px Georgia, Serif; overflow: hidden; resize: none; }
table { border-collapse: collapse; }
table td, table th { border: 1px solid #CCC; padding: 5px; }

#header {
  height: 15px; width: 100%; background: #222; text-align: center; color: white; font: bold 15px Helvetica, Sans-Serif; text-decoration: uppercase; letter-spacing: 20px; padding: 8px 0px;
  // margin: 20px 0;
}

#address { width: 250px; height: 150px; float: left; }
#customer { overflow: hidden; }

#logo { text-align: right; float: right; position: relative; margin-top: 25px; border: 1px solid #fff; max-width: 540px; max-height: 100px; overflow: hidden; }
#logo:hover, #logo.edit { border: 1px solid #CCC; margin-top: 0px; max-height: 125px; }
#logoctr { display: none; }
#logo:hover #logoctr, #logo.edit #logoctr { display: block; text-align: right; line-height: 25px; background: #eee; padding: 0 5px; }
#logohelp { text-align: left; display: none; font-style: italic; padding: 10px 5px;}
#logohelp input { margin-bottom: 5px; }
.edit #logohelp { display: block; }
.edit #save-logo, .edit #cancel-logo { display: inline; }
.edit #image, #save-logo, #cancel-logo, .edit #change-logo, .edit #delete-logo { display: none; }
#customer-title { font-size: 20px; float: left; }

#meta { margin-top: 1px; width: 300px; float: right; }
#meta td { text-align: right;  }
#meta td.meta-head { text-align: left; background: #eee; }
#meta td textarea { width: 100%; height: 20px; text-align: right; }

#items { clear: both; width: 100%; margin: 30px 0 0 0; border: 1px solid #CCC; }
#items th { background: #eee; }
#items textarea { width: 80px; height: 50px; }
#items tr.item-row td { border: 0; vertical-align: top; }
#items td.description { width: 300px; }
#items td.item-name { width: 175px; }
#items td.description textarea, #items td.item-name textarea { width: 100%; }
#items td.total-line { border-right: 0; text-align: right; }
#items td.total-value { border-left: 0; padding: 10px; }
#items td.total-value textarea { height: 20px; background: none; }
#items td.balance { background: #eee; }
#items td.blank { border: 0; }

#terms { text-align: left; margin: 20px 0 0 0; }
#terms h5 { font: 13px Helvetica, Sans-Serif; font-weight:bold; margin: 0 0 3px 0; }
#terms textarea { width: 100%; text-align: center;}

textarea:hover, textarea:focus, #items td.total-value textarea:hover, #items td.total-value textarea:focus, .delete:hover { background-color:#EEFF88; }

.delete-wpr { position: relative; }
.delete { display: block; color: #000; text-decoration: none; position: absolute; background: #EEEEEE; font-weight: bold; padding: 0px 3px; border: 1px solid; top: -6px; left: -22px; font-family: Verdana; font-size: 12px; }

/* Override bootstrap styling  */
textarea.description, input.price, input.qty, textarea#invoice_notes{
  -webkit-box-shadow:none;
  box-shadow:none;
  border:none;
  
}

textarea#invoice_notes{
  text-align:left;
}
</style>

<div class="page-header">
  <h1><%= t ".invoice" %>: <%= @invoice.invoice_number %></h1>
</div>

<div id="page-wrap">

		<!-- <textarea id="header"><%= t '.invoice' %></textarea> -->
		
		<div id="identity">
		
            <span id="address">
            Leonel Santos<br />
            Jose Guadiana #123<br />
            Colonia Centro<br />
            Sabinas Hidalgo, NL 53719<br />
            Telefono: (824) 242-5555
            </span>

            <div id="logo">
              <img id="image" src="/assets/logo.png" alt="logo">
            </div>
		
		</div>
		
		<div style="clear:both"></div>
		
		<div id="customer">

            <span id="customer-title">
              <%= simple_format @invoice.organization.formatted %>
            </span>

            <table id="meta">
                <tbody>
                <tr>
                  <td class="meta-head"><%= t '.invoice_number'%></td>
                  <td><%= @invoice.invoice_number %></td>
                </tr>
                <tr>
                  <td class="meta-head"><%= t '.issued_date' %></td>
                  <td><%= @invoice.read_date_issued_on %></td>
                </tr>
                <!--
                <tr>
                    <td class="meta-head">Amount Due</td>
                    <td><div class="due"><%= number_to_currency @invoice.total %></div></td>
                </tr>
                -->

            </tbody></table>
		
		</div>
		
		<table id="items">
		
		  <tbody><tr>
		      <th><%= t '.item' %></th>
		      <th><%= t '.description' %></th>
		      <th><%= t '.unit_cost' %></th>
		      <th><%= t '.quantity' %></th>
		      <th><%= t '.line_total' %></th>
		  </tr>
		  
		  <% @invoice.line_items.each do |line_item| %>
        <tr class="item-row" style="border-bottom:1px solid #e5e5e5;">
          <td class="item-name" style="padding:2px 2px 2px 5px;">
            <div class="delete-wpr">
		          <span><%= line_item.item.name %></span>
		        </div>
          </td>
          <td class="description">
            <% desc = simple_format line_item.description %>
            <% desc = desc[3..-5] %>
            <span><%= desc %></span>
          </td>
          <td class="price_data"><span class="cost"><%= number_with_precision(line_item.price, :precision =>2 ) %></span></td>
          <td class="quantity_data"><span class="qty"><%= line_item.quantity %></span></td>
          <td class="linetotal_data" style="padding-right:5px;"><span class="price"><%= number_with_precision(line_item.line_total, :precision => 2) %></span></td>
        </tr>
      <% end %>


		  <tr>
		      <td colspan="2" class="blank"> </td>
		      <td colspan="2" class="total-line">Subtotal</td>
		      <td class="total-value" style="text-align:right;"><%= number_to_currency @invoice.subtotal %></td>
		  </tr>
		  
		  <tr>
		      <td colspan="2" class="blank"> </td>
		      <td colspan="2" class="total-line">IVA</td>
		      <td class="total-value" style="text-align:right;"><%= number_to_currency @invoice.iva %></td>
		  </tr>

		  <tr>
		      <td colspan="2" class="blank"> </td>
		      <td colspan="2" class="total-line">Total</td>
		      <td class="total-value" style="text-align:right;"><%= number_to_currency @invoice.total %></td>
		  </tr>
		  
		  <!--
		  <tr>
		      <td colspan="2" class="blank"> </td>
		      <td colspan="2" class="total-line">Amount Paid</td>
		      <td class="total-value"><textarea id="paid">$0.00</textarea></td>
		  </tr>
		  -->
		  
		  <!--
		  <tr>
		      <td colspan="2" class="blank"> </td>
		      <td colspan="2" class="total-line balance">Balance Due</td>
		      <td class="total-value balance"><div class="due">$875.00</div></td>
		  </tr>
		  -->
		
		</tbody></table>
		
		<div id="terms">
		  <h5><%= t '.notes' %></h5>
		  <%= @invoice.notes %>
		</div>
	
	</div>

<div class="form-actions">
  <%= link_to t('buttons.back'),
              invoices_path, :class => 'btn'  %>
  <%= link_to t('buttons.edit'),
              edit_invoice_path(@invoice), :class => 'btn' %>
  <%= link_to t('buttons.destroy'),
              invoice_path(@invoice),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>