config/routes.rb
Facturadormx::Application.routes.draw do

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do

    resources :accounts
    resources :companies
    
    devise_for :users
    # override
    get "accounts/new" => "accounts#new", :as => "new_user_registration"
    
    get "dashboard/index" => 'dashboard#index'
    resources :people

    resources :line_items
    resources :items
    resources :invoices
    resources :organizations

    root :to => "dashboard#index"
    
  end
  match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  match '', to: redirect("/#{I18n.default_locale}")

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>facturadormx</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js" %>
  <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css" %>

  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

 <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">Facturador MX</a>
        <div class="nav-collapse">
        <% if user_signed_in? %>
          <ul class="nav">
            <li><%= link_to t("dashboards.index.title"), dashboard_index_path %></li>
            <li><%= link_to t("organizations.index.title"), organizations_path %></li>
            <li><%= link_to t("invoices.index.title"), invoices_path %></li>
            <li><%= link_to t("items.index.title"), items_path %></li>
          </ul>
          <ul class="nav pull-right">
            <li class="divider-vertical"></li>
            <li><%= link_to "English", locale: "en" %></li>
            <li class="divider-vertical"></li>
            <li><%= link_to "Spanish", locale: "es" %></li>
            <li class="divider-vertical"></li>
            <!--
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
              </ul>
            </li>
            <li class="divider-vertical"></li>
            -->
            <li><a><%= current_user.email %></a></li>
            <li class="divider-vertical"></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t("accounts.show.title") %> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to t('nav.my_profile'), edit_account_path(current_user.account) %></li>
                <li><%= link_to t('nav.company_profile'), edit_company_path(current_user.account.company) %></li>
              </ul>
            </li>            
            <li class="divider-vertical"></li>
            <li><%= link_to t("users.sign_out"), destroy_user_session_path, :method => :delete %></li>
          <% else %>
          <ul class="nav">
            <li><%= link_to (t "users.sign_in.title"), new_session_path(:user) %></li>
            <li class="divider-vertical"></li>
            <li><%= link_to (t "users.sign_up.title"), new_account_path %></li>
          </ul>
          <ul class="nav pull-right">
            <li>
              <%= link_to "English", locale: "en" %>
            </li>
            <li class="divider-vertical"></li>
            <li>
              <%= link_to "Spanish", locale: "es" %>
            </li>
          </ul>
          <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>

<div class="container">

  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">×</a>
      <%= msg %>
    </div>
  <% end %>

  <div class="row">
    <div class="span12"><%= yield %></div>
  </div>
</div>

</body>
</html>